# Site settings
title: IfReturn's Blog
email: yzc2004.12@qq.com
description: >- # this means to ignore newlines until "baseurl:"
  Welcome to my personal blog where I share my thoughts on programming,
  technology, and life experiences.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ifreturn.github.io" # the base hostname & protocol for your site
twitter_username: none
github_username: IfReturn

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title:output_ext

# Pagination
paginate: 10
paginate_path: "/page:num/"
